#!/usr/bin/env bash

echo "[Visulog] Welcome ${USER} !"
toold()
{
while true; do
  echo "[Visulog] Please enter your git repository link or path :"
  read rea
  if [ "$rea" = "" ]; then
    echo "[Visulog] Running Visulog on this Visulog project as an example... (Advanced analysis)"
    ./gradlew run
  else
    echo "[Visulog] Please enter 'y' if you want an advanced analysis (it will take more time !), else for a simple analysis enter 'n' :"
    read ana
    echo "[Visulog] Running Visulog on ${rea}...";
    if [ "$ana" = "y" ]; then
      echo -e "\t(Advanced analysis)";
      ./gradlew run --args="--advancedMode=1 ${rea}";
    else
      echo -e "\t(Simple analysis)";
      ./gradlew run --args=${rea}
    fi
  fi;

  read -p "[Visulog] Do you want to stop doing analysis ? ('y'/'n')" yn
  case $yn in
        [Nn]* ) ;;
        [Yy]* ) echo "[Visulog] Thanks for using Visulog !"; exit;;
        * ) ;;
  esac
done
}

help()
{
  echo "[Visulog] Usage: ./run [-a | -s] <link/path>"
  echo "                 ./run [-t]"
  echo "                 ./run [-h]"
  echo -e "Options :"
  echo -e "   -s \tfor a simple analysis (it includes stats on Commits Per\n\t Month/Day/Hour/Author and the Total of (merged) commits)"
  echo -e "   -a \tfor an advanced analysis (it could take more time! \n\tIt includes all plugins, see README.md for an exhaustive list)"
  echo -e "   -h \tto display this"
  echo ""
  echo -e "   -t \tto run an interactive script (useful if you have differents analysis to do)"
  echo -e ""
  echo -e "Examples :"
  echo -e "   ./run -a  https://github.com/Homebrew/install \n\tto run an advanced analysis on homebrew-install repository"
  echo -e "   ./run -s . \n\tto run a simple analysis on this repository"
  echo ""
  echo -e "Remarks :"
  echo -e "   Writting both -s and -a will automatically let Visulog choose the last one"
  echo -e "   See README.md if any errors occurs"
  echo ""
  echo -e "Authors :"
  echo -e "   LN Supremacy Team"
}
s="0"

while getopts ":hsat" option; do
   case $option in
        h ) help exit;;
        s ) s="1" ;;
        a ) s="0" ;;
        t ) toold exit;; # Appel à un script auxiliaire comme l'ancien mais avec les paths
        [^hsat]* ) help exit;;
  esac
done

if [ "$1" = "" ] || [ "$2" = "" ]; then
  help
  #exit 1
else
  if [ "$s" = "1" ]; then
    echo "[Visulog] Running Visulog on \"${2}\" using simple mode"
    ./gradlew run --args="${2}"
  else
    echo "[Visulog] Running Visulog on \"${2}\" using advanced mode"
    ./gradlew run --args="--advancedMode=1 ${2}"
  fi
fi


